// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3smqDt_oqwce7x1FGvsZtkx3Qmbp2SR0',
    appId: '1:572686016656:web:f41f7cc59a8b95ba49b815',
    messagingSenderId: '572686016656',
    projectId: 'demoapp-14cc0',
    authDomain: 'demoapp-14cc0.firebaseapp.com',
    storageBucket: 'demoapp-14cc0.firebasestorage.app',
    measurementId: 'G-P71H6BRSYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJsd71ggLkEDPz27vPo3S60Zck7MmoIAE',
    appId: '1:572686016656:android:5ee1251a5041425d49b815',
    messagingSenderId: '572686016656',
    projectId: 'demoapp-14cc0',
    storageBucket: 'demoapp-14cc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9znc9_EVzNUi2O0O7F68dVhhc9I7_tPc',
    appId: '1:572686016656:ios:aa5a4b36f601780149b815',
    messagingSenderId: '572686016656',
    projectId: 'demoapp-14cc0',
    storageBucket: 'demoapp-14cc0.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9znc9_EVzNUi2O0O7F68dVhhc9I7_tPc',
    appId: '1:572686016656:ios:aa5a4b36f601780149b815',
    messagingSenderId: '572686016656',
    projectId: 'demoapp-14cc0',
    storageBucket: 'demoapp-14cc0.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3smqDt_oqwce7x1FGvsZtkx3Qmbp2SR0',
    appId: '1:572686016656:web:21c861f127257a5749b815',
    messagingSenderId: '572686016656',
    projectId: 'demoapp-14cc0',
    authDomain: 'demoapp-14cc0.firebaseapp.com',
    storageBucket: 'demoapp-14cc0.firebasestorage.app',
    measurementId: 'G-S3E0X7ZE8R',
  );
}
